#!/usr/bin/env bash

function dispatch() {
  local COMMANDS=('qa' 'tests' 'cs' 'psalm' 'help' '--help' '-h' 'down')
  local BASE_CMD="composer install --no-progress --no-suggest -q -o -n && composer"
  local COMMAND=$1
  local CMD
  local ERROR=0

  # Command not recognized, print error then set command to help. Make sure exist code is 1.
  # shellcheck disable=SC2076
  if [[ ! " ${COMMANDS[*]} " =~ " $COMMAND " ]]; then
    if [[ "$COMMAND" != '' ]]; then
      printf "Error: the command '%s' does not exist.\n" "$COMMAND"
    else
      printf "Error: wrong usage.\n"
    fi

    COMMAND='help'
    ERROR=1
  fi

  if [[ "$COMMAND" = "help" ]] || [[ "$COMMAND" = "--help" ]] || [[ "$COMMAND" = "--h" ]]; then
    printf "\nUsage:\n"
    printf "\$ docker-run <command>\n\n"
    printf "Commands:\n"
    printf " - \"tests\" : Execute PHP unit tests.\n"
    printf " - \"cs\"    : Check code styles with PHPCS.\n"
    printf " - \"psalm\" : Check code with Psalm.\n"
    printf " - \"qa\"    : Execute all above.\n"
    printf " - \"down\"  : Shortcut to 'docker-compose down --volumes' in proper folder.\n"

    exit ${ERROR}
  fi

  if [[ "$COMMAND" = "down" ]]; then
    cd 'tests/docker' && docker-compose down --volumes
    exit 0
  fi

  if [[ "$COMMAND" = "tests" ]]; then
    COMMAND="tests:no-cov"
  fi

  CMD="$BASE_CMD $COMMAND"

  if [[ "$COMMAND" = "tests:no-cov" ]] || [[ "$COMMAND" = "qa" ]]; then
    CMD="wait-for.sh dbal-mysql:3306 -t 15 -- $CMD"
  fi

  printf "Executing '%s'...\n" "$CMD"
  cd 'tests/docker' && docker-compose run --rm -T code sh -c "$CMD"
}

# And go!
dispatch "$1"
