name: Code Style

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '**/code-style.yml'
            - 'composer.*'
            - 'phpcs*'
            - '**.php'
    push:
        paths:
            - '**/code-style.yml'
            - 'composer.*'
            - 'phpcs*'
            - '**.php'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    php-coding-standards-check:
        if: ${{ !contains(github.event.head_commit.message, 'cs skip') }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
        secrets:
            COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}