name: PHP integration tests
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['72', '73', '74']
        steps:
            -   uses: actions/checkout@v2

            -   name: Copy wait-for script
                uses: canastro/copy-file-action@master
                with:
                    source: "tests/docker/wait-for.sh"
                    target: "tests/docker/php-${{ matrix.php-versions }}/wait-for.sh"

            -   name: Run integration tests
                working-directory: ./tests/docker
                run: docker-compose run -T php${{ matrix.php-versions }} sh -c "wait-for.sh fasti-mysql:3306 -t 15 -- && composer install -q -n -a --no-progress --prefer-dist && composer tests:integration"
