name: Integration Tests

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '**.php'
            - 'phpunit*'
            - 'composer.*'
    push:
        paths:
            - '**.php'
            - 'phpunit*'
            - 'composer.*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests-integration-php:
        if: ${{ !contains(github.event.head_commit.message, 'integration-tests skip') }}
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.2', '8.3', '8.4' ]
                wp-version: [ '6.8', '6.9', '7.0' ]
        uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
        secrets:
            COMPOSER_AUTH_JSON: ${{ secrets.PACKAGIST_AUTH_JSON }}
            ENV_VARS: >-
                [{"name":"WP_CORE_VERSION", "value":"${{ matrix.wp-version }}"}]
        with:
            PHP_VERSION: ${{ matrix.php-version }}
            PHPUNIT_ARGS: '--testsuite=integration --no-coverage -c phpunit-integration.xml.dist'
