name: Integration Tests

on:
    workflow_dispatch:
    pull_request:
        paths:
            - '**/integration-tests*'
            - '**/docker/**'
            - '**.php'
            - 'phpunit*'
    push:
        paths:
            - '**/integration-tests*'
            - '**/docker/**'
            - '**.php'
            - 'phpunit*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'integration-tests skip') }}
        strategy:
            matrix:
                php-version: [ '7.2', '7.3', '7.4', '8.0' ]
                wp-version: [ '5.8', '5.9', '6.0' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Save Docker images cache
                uses: actions/cache@v3
                with:
                    path: /var/lib/docker/overlay2
                    key: ${{ runner.os }}-docker-images

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none

            -   name: Adjust Composer Dependencies
                run: |
                    composer config --unset repositories.0
                    composer remove inpsyde/php-coding-standards inpsyde/wp-stubs vimeo/psalm roots/wordpress --dev --no-update
                    composer require roots/wordpress:${{ matrix.wp-version }} --no-update

            -   name: Install Composer Dependencies
                uses: ramsey/composer-install@v2

            -   name: Run integration tests
                working-directory: ./tests
                run: |
                    chmod u+x ./integration-tests.sh
                    ./integration-tests.sh ${{ matrix.php-version }}
