name: Static Analysis

on:
  push:
    paths:
      - '**workflows/static-analysis.yml'
      - '**.php'
      - '**phpcs.xml.dist'
      - '**psalm.xml'
      - '**composer.json'
  pull_request:
    paths:
      - '**workflows/static-analysis.yml'
      - '**.php'
      - '**phpcs.xml.dist'
      - '**phpstan.neon.dist'
      - '**composer.json'
  workflow_dispatch:
    inputs:
      jobs:
        required: true
        type: choice
        default: 'Run all'
        description: 'Choose jobs to run'
        options:
          - 'Run all'
          - 'Run PHPCS only'
          - 'Run PHPStan only'
          - 'Run lint only'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-php:
    uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
    if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run lint only') || (github.event.inputs.jobs == 'Run all')) }}
    strategy:
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
    with:
      PHP_VERSION: ${{ matrix.php }}

  coding-standards-analysis-php:
    if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run PHPCS only') || (github.event.inputs.jobs == 'Run all')) }}
    uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main
    with:
      PHP_VERSION: '8.2'

  static-code-analysis-php:
    if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run PHPStan only') || (github.event.inputs.jobs == 'Run all')) }}
    uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
    with:
      PHP_VERSION: '8.4'
